name: Deploy NiCiStore to GitHub Pages

on:
  push:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
    - name: Build and Deploy
      uses: phucphan-dev/nici-closet@v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build