name: Build and Publish to GitHub Pages

on:
  push:
    branches:
      - "develop"
jobs:
  deploy:
    environment:
      name: github-pages
      url: https://nicistore.online/
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: build
        build_command: npm run build